### ISSUE TITLE
Email grammar too complex (Lpeg 0.12)

### ISSUE THREAD

**Issue by daurnimator** [spc476/LPeg-Parsers#2]
After filing Issue #1 I upgraded my lpeg:

```
$ lua -l lpeg -e "print(lpeg.version())"
0.12
```

Now I get an entirely different error :)

```
$ lua ../LPeg-Parsers/email.lua
lua: bad argument #1 to '?' (grammar has too many rules)
stack traceback:
        [C]: ?
        [C]: in function 'match'
        /usr/local/share/lua/5.1/re.lua:208: in function </usr/local/share/lua/5.1/re.lua:206>
        (tail call): ?
        [C]: ?
```

**Comment by aklt** [comment]
I ran into what I think is the same or at least a similar issue and
would like to use this parser, so consider this a note.

```sh
# lua -v
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
# lua -l lpeg -e "print(lpeg.version())"
1.0.0
```

If I run

```lua
print(inspect(email:match(myEmail)))
```
on the email in the example it causes a core dump on my machine and gdb shows that there 
is a huge stack from somewhere in `lpeg.so`. 

A simmilar bug is described here, but not fixed in lpeg 1.0.0:

    http://lua-users.org/lists/lua-l/2016-09/msg00155.html

    http://lua-users.org/lists/lua-l/2016-09/msg00189.html

**Comment by spc476** [comment]
It works with LPeg 1.0.1.  I've updated the rockspec so if you use LuaRocks, it should be an easy to reinstall both.

**Comment by aklt** [comment]
Cool, thanks!
